name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REGION: europe-west4
      SERVICE_NAME: reports-service
      REPO_NAME: reports-service
      VPC_CONNECTOR: marklie-vpc
      REDIS_HOST: 10.x.x.x:6379

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Set up Google Cloud SDK'
        uses: google-github-actions/setup-gcloud@v4
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authorize Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -f ./docker/Dockerfile -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA .

      - name: Push Docker image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA \
            --region=${{ env.REGION }} \
            --platform=managed \
            --vpc-connector=${{ env.VPC_CONNECTOR }} \
            --set-env-vars=REDIS_HOST=${{ env.REDIS_HOST }} \
            --allow-unauthenticated
