name: Deploy to Cloud Run

on:
  push:
    branches: [main, staging]

env:
  PROJECT_ID: saas-452909
  REGION: europe-west4
  REGISTRY: europe-west4-docker.pkg.dev
  IMAGE_NAME: reports-service
  IMAGE_REPO: europe-west4-docker.pkg.dev/saas-452909/reports-service

permissions:
  contents: read
  id-token: write

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: saas-452909
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: github-deployer@saas-452909.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Build image
        run: |
          docker build \
            -f docker/Dockerfile \
            -t ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:staging-${{ github.sha }} .

      - name: Push image
        run: docker push ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:staging-${{ github.sha }}

      - name: Deploy to Cloud Run (staging)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.IMAGE_NAME }}-staging
          image: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:staging-${{ github.sha }}
          env_vars: |
            ENVIRONMENT=staging

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: saas-452909
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: github-deployer@saas-452909.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Build image
        run: |
          docker build \
            -f docker/Dockerfile \
            -t ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:prod-${{ github.sha }} .

      - name: Push image
        run: docker push ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:prod-${{ github.sha }}

      - name: Deploy to Cloud Run (production)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.IMAGE_NAME }}
          image: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:prod-${{ github.sha }}
          env_vars: |
            ENVIRONMENT=production
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}